spring:
  application:
    name: zuul-server
server:
  port: 8762
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceURL:
    defaultZone: ${EUREKA_URI:http://localhost:8761:eureka}
endpoints:
  routes:
    sensitive: false
zuul:
  routes:
    e-p:
      path: /e-p/**
      #url: http://localhost:8762/employee-producer/
      serviceId: EMPLOYEE-PRODUCER #Id from Eureka to avaoid hardcoding